# Supabase Configuration
# This file is automatically used by the Supabase CLI

project_id = "omxporaecrqsqhzjzvnx"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://sanluisway.com"]